### ISSUE TITLE
Warning of possible problems with firebase messaging

### ISSUE THREAD

**Issue by Lipe1994** [BatchLabs/Batch-Flutter-Plugin#5]
I set up Batch in a flutter project for IOS and android following the documentation found at https://doc.batch.com/flutter/sdk-integration/

My problem is that because it is configured for Android, it uses firebase messaging. And Firebase Messaging causes some warnings in the log when launching on IOS.

Warning:

```
Launching lib/main.dart on iPhone 14 Pro Max in debug mode...
lib/main.dart:1
Xcode build done.                                           26.8s
Batch started with a DEV API key
Installation ID: 18A985DC-05CC-4644-9D52-77336A3D9547
⚠️ Firebase has been detected in your application, but Batch's manual integration has NOT been enabled.
⚠️ This can cause issues with Batch's handling of notifications:
⚠️ Direct Opens, Mobile Landings and Deeplinks might not work
⚠️ More info about the manual integration here: https://batch.com/doc/ios/advanced/manual-integration.html
⚠️ The App Group 'group.br.com.cetelem.app.debug-dev.batch' hasn't been configured. See the documentation for more info: https://doc.batch.com/ios/advanced/app-groups
2
Push token (Apple Push Sandbox/Development): 8081638f20fdc7cfd0c8b98057f1f4bda038aad69200a19685de0c54ded743570de86dafcd87408afa67f63785fb87a936aa0631ef3d1a23937cbf188c66a685d5388c2b410c17b0f8357dcc09bcbeff
Connecting to VM Service at ws://127.0.0.1:49840/-CQRczbeRkk=/ws
```

I don't use firebase messaging in IOS, but because I use it on android I get these warnings... I believe it is a bug, as I have no intention of using firebase messaging for IOS but Batch itself uses it to handle Android notifications.

```
my flutter version:
╰─ flutter doctor                                                                                                                     ─╯
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.0.1 22A400 darwin-arm, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.73.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Comment by abarisain** [comment]
Hi,

While the log is somewhat outdated (it does not cause issues with Direct Opens/landings/etc... since UNUserNotificationDelegate), Firebase can cause Batch to fail to get the APNs token.

Unfortunately there is no good way to know if Firebase is configured or simply there in the code, so the log is triggered when Firebase classes are noticed in your app. This does trigger false positives in multiplatform projects, but has the side effect of informing you that you are shipping unused Firebase code in your iOS app.

I have two suggestions:
- If you only want FCM, try not to use the plugin but integrate it manually in the Android project
- Try to remove the firebase Pods from your iOS project

I opened an internal ticket to update the log, but removing it is not planned.


Have a nice day,
Arnaud
